spring:
  application:
    name: goswami-core
  cloud:
    consul:
      bvg.api.config:
        failFast: false
# ===============================
# = Hibernate datasource
# ===============================
  datasource:
    url: jdbc:postgresql://localhost:5433/goswami
    username: postgres
    password: postgres

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    database-platform: POSTGRESQL
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect

server:
  port: 8088
  servlet-path: /
